import AppKit
import CryptoKit
import Dispatch
import Foundation
import Logging

protocol PasteboardReading: AnyObject {
    var changeCount: Int { get }
    func string(forType type: NSPasteboard.PasteboardType) -> String?
    func data(forType type: NSPasteboard.PasteboardType) -> Data?
    func types() -> [NSPasteboard.PasteboardType]?
}

extension NSPasteboard: PasteboardReading {
    func types() -> [NSPasteboard.PasteboardType]? { self.types }
}

final class PasteboardWatcher: @unchecked Sendable {
    static let ownershipType = NSPasteboard.PasteboardType("com.clipsync.event-nonce")
    private static let jpeg = NSPasteboard.PasteboardType("public.jpeg")
    private static let sensitiveTypes: Set<NSPasteboard.PasteboardType> = [
        .init("org.nspasteboard.ConcealedType"), .init("org.nspasteboard.TransientType"),
        .init("org.nspasteboard.AutoGeneratedType")
    ]
    typealias Snapshot = ClipPayload
    private let pasteboard: PasteboardReading
    private let interval: DispatchTimeInterval
    private let queue = DispatchQueue(label: "clipsync.pasteboard.reducer")
    private var timer: DispatchSourceTimer?
    private var order: ClipboardChangeOrder
    private var enabled = true
    private var continuations: [UUID: AsyncStream<Snapshot>.Continuation] = [:]

    init(pasteboard: PasteboardReading = NSPasteboard.general, intervalMillis: Int = 750,
         logger: Logger = Logger(label: "clipsync.pasteboard.watcher")) {
        self.pasteboard = pasteboard
        interval = .milliseconds(intervalMillis)
        order = ClipboardChangeOrder(baseline: pasteboard.changeCount)
    }

    func start() {
        queue.async { [weak self] in
            guard let self, self.timer == nil else { return }
            let timer = DispatchSource.makeTimerSource(queue: self.queue)
            timer.schedule(deadline: .now() + self.interval, repeating: self.interval)
            timer.setEventHandler { [weak self] in _ = self?.tick() }
            self.timer = timer
            timer.resume()
        }
    }
    func stop() { queue.sync { timer?.cancel(); timer = nil } }
    func setSyncEnabled(_ enabled: Bool) {
        queue.sync {
            self.enabled = enabled
            // Resuming never sends a stale clipboard captured during the pause.
            _ = order.observeLocal(count: pasteboard.changeCount, nowMs: ClipPayload.currentTimestampMillis())
        }
    }
    func events() -> AsyncStream<Snapshot> {
        AsyncStream(bufferingPolicy: .bufferingNewest(1)) { continuation in
            let id = UUID()
            queue.sync { continuations[id] = continuation }
            continuation.onTermination = { [weak self] _ in
                self?.queue.async { self?.continuations.removeValue(forKey: id) }
            }
        }
    }

    /// Clipboard writes and polls share one serial reducer. No asynchronous digest baselining.
    func performRemoteWrite(_ payload: ClipPayload, write: () throws -> Void) throws {
        try queue.sync {
            guard enabled else { throw PasteboardInjectionError.paused }
            // A pending local copy wins. Capture it asynchronously so applying a prepared
            // remote item never triggers image inspection on the caller's UI thread.
            guard pasteboard.changeCount == order.baseline else {
                queue.async { [weak self] in _ = self?.tick() }
                throw PasteboardInjectionError.superseded
            }
            guard order.permitsRemote(timestamp: payload.ts) else { throw PasteboardInjectionError.superseded }
            try write()
            let count = pasteboard.changeCount
            let marker = pasteboard.string(forType: Self.ownershipType)
            let endCount = pasteboard.changeCount
            // If a user copied B after our A, its marker/count cannot be acknowledged as our own write.
            let ownedCount = count == endCount && marker == payload.nonce ? count : nil
            order.acknowledgeRemote(timestamp: payload.ts, exactOwnedCount: ownedCount)
        }
    }

    @discardableResult func pollNow() -> ClipPayload? { queue.sync { tick() } }

    private func tick() -> ClipPayload? {
        let count = pasteboard.changeCount
        guard count != order.baseline else { return nil }
        if !enabled { _ = order.observeLocal(count: count, nowMs: ClipPayload.currentTimestampMillis()); return nil }
        let payload = capturePayload()
        guard count == pasteboard.changeCount else { return nil } // Try the newer complete snapshot next poll.
        guard order.observeLocal(count: count, nowMs: ClipPayload.currentTimestampMillis()) else { return nil }
        if let payload { for continuation in continuations.values { continuation.yield(payload) } }
        return payload
    }

    private func capturePayload() -> ClipPayload? {
        let types = Set(pasteboard.types() ?? [])
        guard types.isDisjoint(with: Self.sensitiveTypes), !types.contains(.fileURL) else { return nil }
        let payload: ClipPayload
        if types.contains(.png), let bytes = pasteboard.data(forType: .png), bytes.count <= ClipPayload.maxImageBytes {
            payload = .image(bytes)
        } else if types.contains(Self.jpeg), let bytes = pasteboard.data(forType: Self.jpeg), bytes.count <= ClipPayload.maxImageBytes {
            payload = .image(bytes, mime: "image/jpeg")
        } else if types.contains(.tiff), let bytes = pasteboard.data(forType: .tiff),
                  let png = try? ClipImageSafety.clipboardTIFFToPNG(bytes) {
            payload = .image(png)
        } else if types.contains(.string), let value = pasteboard.string(forType: .string), value.utf8.count <= ClipPayload.maxTextBytes {
            payload = .text(value)
        } else { return nil }
        guard (try? payload.validate()) != nil else { return nil }
        return payload
    }

    /// Diagnostics/tests only. Echo detection uses exact owned change counts, not content hashes.
    static func digest(for payload: ClipPayload) -> String {
        var hasher = SHA256()
        for part in [payload.type.rawValue, payload.mime, payload.dataBase64, payload.name ?? ""] {
            let bytes = Data(part.utf8)
            hasher.update(data: Data("\(bytes.count):".utf8))
            hasher.update(data: bytes)
        }
        return hasher.finalize().map { String(format: "%02x", $0) }.joined()
    }
}
